### ISSUE TITLE
测试跟打包都有问题啊

### ISSUE THREAD

**Issue by Apibug** [GuoGuang/ibole#6]
<img width="1359" alt="erreo" src="http://chuantu.xyz/t6/715/1581581309x2073530527.png">

图片地址：http://chuantu.xyz/t6/715/1581581309x2073530527.png

**Comment by GuoGuang** [comment]
图片貌似打不开了，请提供下具体异常

**Comment by Apibug** [comment]
<img width="1227" alt="12" src="https://user-images.githubusercontent.com/29590985/78170477-98211a00-7485-11ea-91e9-8ab8af5e633b.png">
那个后端没明白- -

**Comment by GuoGuang** [comment]
后端语言自己决定，只要对外提供接口就可以
